# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  displayName: Terraform Init
- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: 'plan'
    environmentServiceName: 'Free Trial(227b05ae-a33b-4d8b-a744-107732f1f1c4)'
    providerAzureRmSubscriptionId: '227b05ae-a33b-4d8b-a744-107732f1f1c4'
    allowTelemetryCollection: false
  